### ISSUE TITLE
CLI update to `cpy` API v6?

### ISSUE THREAD

**Issue by danielweck** [sindresorhus/cpy-cli#14]
Currently locked on v4:
https://github.com/sindresorhus/cpy-cli/blob/master/package.json#L52
https://github.com/sindresorhus/cpy-cli/blob/a8d4be92011d5e873d16601958df543376257c9e/package.json#L52

`cpy` API:
https://www.npmjs.com/package/cpy
https://unpkg.com/cpy/package.json
https://github.com/sindresorhus/cpy/blob/master/package.json

**Comment by nimojs** [comment]
CLI update to `cpy@7`?
