### ISSUE TITLE
Readme examples don't work in windows powershell - have to use double quotes ("")

### ISSUE THREAD

**Issue by marcospgp** [sindresorhus/cpy-cli#18]

**Comment by marcospgp** [comment]
Found an existing closed issue for this, though the problem wasn't solved. Feel free to close this too though!

**Comment by sindresorhus** [comment]
It's just an example. It's up to you to know how your shell works. It's not a problem with the package or example.

**Comment by marcospgp** [comment]
I would agree but the tool executes and completes silently, giving the
appearance that I made a mistake somewhere.
