### ISSUE TITLE
Initial folder structure not restored in destination folder

### ISSUE THREAD

**Issue by johannchopin** [sindresorhus/cpy-cli#27]
Hey 👋  First thanks for the effort put in this project 👍

I have a project structure that looks like this:

```
project
│
└───node_modules
│   └───module
│       └───public
│           └───dist
│               │ styles.css
│           │ index.html
│   
└───src
```

And I want to copy the `public` folder from `node_modules/module/public` into the `src/public` folder. So I run this command:

```
$ yarn cpy ./node_modules/module/public ./src/public
```

It works but the final `src/public` folder contains all the files but not the initial folder structure:

```
# just the files
│   
└───src
    └───public
        │ styles.css
        │ index.html
```
```
# expected folder structure
│   
└───src
    └───public
        └───dist
            │ styles.css
        │ index.html
```

And if I run it with the `--parents` I got this structure:

```
public
│
└───node_modules
│   └───module
│       └───public
│           └───dist
│               │ styles.css
│           │ index.html
```

Has someone an idea how I could get the expected folder structure?

Thanks in advance 😄

**Comment by sindresorhus** [comment]
I think https://github.com/sindresorhus/cpy/pull/77 will resolve your issue.

**Comment by JounQin** [comment]
@sindresorhus 

Is the following expected??

`cpy node_modules/shiki/{dist,languages,themes} public/shiki --parents`

![image](https://user-images.githubusercontent.com/8336744/132078971-4817d0b0-c52a-41ea-8710-22755200d506.png)

**Comment by sindresorhus** [comment]
This is now fixed in `cpy`, so someone just needs to bring the updates here. https://github.com/sindresorhus/cpy/releases/tag/v9.0.0
