### ISSUE TITLE
option for ignore error if not found files

### ISSUE THREAD

**Issue by evilebottnawi** [sindresorhus/cpy-cli#6]
I run.
```shell
cpy 'public/**/*.*' '../build/' --cwd=src --parents
````
Output:
```shell
Cannot glob `public/**/*.*,!**/*-src.*`: Cannot copy from `/path/to/src/public/**/*.*` to `/path/to/build/public/**/*.*`: cannot read from `/path/to/public/**/*.*`: ENOENT: no such file or directory, open '/path/to/src/public/**/*.*'
```

**Comment by schnittstabil** [comment]
@evilebottnawi Hmm, what exactly bothers you? The message, the exit code or both? – Can you give us some context, why this feature is useful for you?

**Comment by evilebottnawi** [comment]
@schnittstabil exit code, i use CI and get build failed.

**Comment by schnittstabil** [comment]
You may try `|| true`, which is perhaps not platform independent, though:
```bash
cpy 'public/**/*.*' '../build/' --cwd=src --parents || true
```

**Comment by evilebottnawi** [comment]
@schnittstabil it is normal use for build on window and other os?

**Comment by evilebottnawi** [comment]
@schnittstabil thanks

**Comment by schnittstabil** [comment]
The double pipe (`||`) is supported by windows, but not the `true` command afaik.
For `package.json/"scripts"` use cases you may install a cross-platform implementation, e.g. [cash-true](https://www.npmjs.com/package/cash-true):
```bash
npm install --save-dev cash-true
```
