### ISSUE TITLE
Windows CI

### ISSUE THREAD

**Issue by schnittstabil** [sindresorhus/cpy-cli#8]
With all the path handling stuff, I think, the CLI would profit from testing on Windows too. 

@sindresorhus Would you mind to add support for Appveyor? At least for me, it's a bit cumbersome to run tests on Windows.

Btw, this may also be convenient for `cpy` and `cp-file`.

**Comment by sindresorhus** [comment]
I don't see the point here, as it's just a tiny CLI wrapper over `cpy`, but I'll set it up on `cp-file` and `cpy` when I have time.

**Comment by schnittstabil** [comment]
I have concerns about escaping issues too, like #9. However, of course, `cpy-cli` is tiny and these are easy to tackle…

**Comment by sindresorhus** [comment]
It's just that AppVeyor is annoying to set up and really slow and unstable, so I try to only use it when absolutely necessary.

**Comment by schnittstabil** [comment]
In that case, we may reconsider this until we have *real world* windows issues.
